#!/usr/bin/env node
/**
 * build-sitemap.js — regenerate sitemap.xml from the live catalogue.
 *
 *   node scripts/build-sitemap.js            # write sitemap.xml
 *   node scripts/build-sitemap.js --dry-run  # print, change nothing
 *   node scripts/build-sitemap.js --json     # machine-readable summary
 *
 * Why this exists
 * ---------------
 * sitemap.xml used to be a hand-maintained file containing a single URL — even
 * though the site now serves real pages at /coupon/:id, /store/:id and
 * /category/:id. Hand-maintained SEO files always drift; this derives the
 * sitemap from data/*.json so it cannot.
 *
 * Indexing policy
 * ---------------
 * Only pages with real content are listed. A store with zero coupons renders an
 * empty page, which is thin content, so it is excluded here AND marked
 * <meta name="robots" content="noindex,follow"> by api/page.js. Both halves are
 * needed: the sitemap keeps crawlers out, the meta tag keeps out those that
 * arrive by another route.
 *
 * Expired coupons are excluded — linking to a dead offer is worse than not
 * linking at all.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const S = require('../api/_secrets.js');

const ROOT = path.join(__dirname, '..');
const DATA = path.join(ROOT, 'data');

const argv = process.argv.slice(2);
const has = f => argv.includes(f);
const AS_JSON = has('--json');
const DRY_RUN = has('--dry-run');

const SITE = (S.env('SITE_URL', 'https://nipcoupon.vercel.app').trim() || 'https://nipcoupon.vercel.app').replace(/\/+$/, '');

function read(f) {
  return JSON.parse(fs.readFileSync(path.join(DATA, f), 'utf8'));
}

function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

/** Today, YYYY-MM-DD — used as lastmod for pages without a meaningful date. */
function today() { return new Date().toISOString().slice(0, 10); }

/** lastmod must be a valid date; fall back to today rather than emit junk. */
function lastmod(value) {
  if (!value) return today();
  const t = Date.parse(value);
  return Number.isNaN(t) ? today() : new Date(t).toISOString().slice(0, 10);
}

const stores = read('stores.json').stores || [];
const coupons = read('coupons.json').coupons || [];
const categories = read('categories.json').categories || [];

const now = Date.now();
const live = coupons.filter(c => !(c.active === false));
const fresh = live.filter(c => {
  if (!c.expires) return true;
  const t = Date.parse(c.expires);
  return Number.isNaN(t) || t >= now;
});

/* How many live coupons each store / category actually has. */
const perStore = {};
const perCat = {};
fresh.forEach(c => {
  perStore[c.storeId] = (perStore[c.storeId] || 0) + 1;
  perCat[c.categoryId] = (perCat[c.categoryId] || 0) + 1;
});

const urls = [];

/* Home — the highest-value page. */
urls.push({
  loc: SITE + '/',
  lastmod: today(),
  changefreq: 'daily',
  priority: '1.0'
});

/* Categories that have deals. */
categories.filter(c => (perCat[c.id] || 0) > 0).forEach(c => {
  urls.push({
    loc: SITE + '/category/' + encodeURIComponent(c.id),
    lastmod: today(),
    changefreq: 'daily',
    priority: '0.8'
  });
});

/* Stores that have deals — the 30 empty ones stay out by design. */
stores.filter(s => (perStore[s.id] || 0) > 0).forEach(s => {
  urls.push({
    loc: SITE + '/store/' + encodeURIComponent(s.id),
    lastmod: today(),
    changefreq: 'daily',
    priority: '0.7'
  });
});

/* Individual offers. */
fresh.forEach(c => {
  urls.push({
    loc: SITE + '/coupon/' + encodeURIComponent(c.id),
    lastmod: lastmod(c.expires),
    changefreq: 'weekly',
    priority: c.hot ? '0.6' : '0.5'
  });
});

/* ── hreflang ────────────────────────────────────────────────────────────────
 * Every URL is published in two languages, so every entry declares both plus
 * an x-default. Without this Google can only guess which language to rank for
 * which market, and Arabic pages end up competing with their English twins.
 *
 * Locales come from locales/*.json, the same source api/i18n.js serves, so
 * dropping in fr.json adds French here on the next build with no edit. */
const LOCALES_DIR = path.join(ROOT, 'locales');
const LOCALES = (function () {
  try {
    return fs.readdirSync(LOCALES_DIR)
      .filter(f => f.endsWith('.json'))
      .map(f => f.replace(/\.json$/, ''))
      .sort();
  } catch (e) {
    return ['en'];
  }
})();
const DEFAULT_LOCALE = LOCALES.indexOf('en') !== -1 ? 'en' : LOCALES[0];

function alternates(loc) {
  const join = loc.indexOf('?') === -1 ? '?' : '&';
  return LOCALES.map(l =>
    '    <xhtml:link rel="alternate" hreflang="' + l + '" href="' + esc(loc + join + 'lang=' + l) + '"/>'
  ).concat([
    '    <xhtml:link rel="alternate" hreflang="x-default" href="' + esc(loc) + '"/>'
  ]).join('\n');
}

const xml =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<!-- Generated by scripts/build-sitemap.js — do not edit by hand. -->\n' +
  '<!-- ' + urls.length + ' URLs · ' + LOCALES.length + ' locales · ' + new Date().toISOString() + ' -->\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n' +
  '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n' +
  urls.map(u =>
    '  <url>\n' +
    '    <loc>' + esc(u.loc) + '</loc>\n' +
    alternates(u.loc) + '\n' +
    '    <lastmod>' + u.lastmod + '</lastmod>\n' +
    '    <changefreq>' + u.changefreq + '</changefreq>\n' +
    '    <priority>' + u.priority + '</priority>\n' +
    '  </url>'
  ).join('\n') +
  '\n</urlset>\n';

if (!DRY_RUN) fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), xml);

const summary = {
  written: !DRY_RUN,
  total: urls.length,
  home: 1,
  categories: categories.filter(c => (perCat[c.id] || 0) > 0).length,
  storesListed: stores.filter(s => (perStore[s.id] || 0) > 0).length,
  storesExcludedEmpty: stores.filter(s => (perStore[s.id] || 0) === 0).length,
  couponsListed: fresh.length,
  couponsExcludedExpired: live.length - fresh.length,
  locales: LOCALES,
  hreflangEntries: urls.length * (LOCALES.length + 1),
  file: 'sitemap.xml'
};

if (AS_JSON) {
  console.log(JSON.stringify(summary, null, 2));
} else {
  console.log('');
  console.log('Sitemap — ' + (DRY_RUN ? 'dry run' : 'written to sitemap.xml'));
  console.log('─'.repeat(52));
  console.log('  home                : ' + summary.home);
  console.log('  categories          : ' + summary.categories + ' of ' + categories.length);
  console.log('  stores (with deals) : ' + summary.storesListed);
  console.log('  stores (empty, skip): ' + summary.storesExcludedEmpty);
  console.log('  coupons             : ' + summary.couponsListed);
  console.log('  coupons (expired)   : ' + summary.couponsExcludedExpired);
  console.log('  ── total URLs       : ' + summary.total);
  console.log('  locales             : ' + LOCALES.join(', '));
  console.log('  hreflang entries    : ' + summary.hreflangEntries);
  console.log('');
}
